services:
  db:
    platform: linux/amd64
    container_name: mysql-server
    image: mysql:latest
    ports:
      - 3306:3306
    volumes: 
      - /home/ubuntu/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fandoms
      MYSQL_USER: fans
      MYSQL_PASSWORD: fans
    networks:
      - fans-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  backend:
    platform: linux/amd64
    container_name: fans_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fans-network

networks:
  fans-network:
    driver: bridge
